RUNTIME_NAME = "Transformer_multilabel-classification_mean"
# BASE_DIR = "/home/Ravikumar/Developer/Learning-NLP-with-PyTorch/"
BASE_DIR = "/content/drive/MyDrive/Learning-NLP-with-PyTorch/"
WORKING_DIR = "Chapter - 7 : Detailed Understanding of Multi-Label Classification/"
TRAIN_DIR = BASE_DIR +WORKING_DIR + "dataset/prep_train_data.csv"
TEST_DIR = BASE_DIR +WORKING_DIR + "dataset/test.csv"
TEST_PRE_DIR = BASE_DIR +WORKING_DIR + "dataset/prep_test_data.csv"
DATASET_DIR = BASE_DIR +WORKING_DIR + "dataset/"
LABELS = ['Computer Science', 'Physics', 'Mathematics','Statistics', 'Quantitative Biology', 'Quantitative Finance']
SPLIT_DATA_DIR = BASE_DIR + WORKING_DIR + "dataset/splitted_data.pt"
VOCAB_DIR = BASE_DIR + WORKING_DIR + "dataset/vocab.json"
NUM_LABELS = 6
MAX_LEN = 450
DEVICE = 'cuda'
EPOCHS = 2
BATCH_SIZE = 64
LEARNING_RATE = 1e-4
PATIENCE = 3
CHECKPOINT_DIR = BASE_DIR + WORKING_DIR +"dataset/checkpoints/"
CHECKPOINT_NAME = CHECKPOINT_DIR + f"{RUNTIME_NAME}_bs_{BATCH_SIZE}_lr_{LEARNING_RATE}.pt"
EMBED_SIZE = 32
HIDDEN_SIZE = 512
N_HEAD = 8
N_LAYERS = 6
STEP_SIZE = 5
GAMMA = 0.1